
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser,  } from "@fortawesome/free-regular-svg-icons";
import { faBagShopping } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sport's mood",
  description: "Generated by Beka Dugladze",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="
        flex 
        row 
        justify-around 
        items-center fixed 
        bottom-0 
        tablet:top-0
        tablet:bottom-auto
        w-full 
        bg-white 
        z-50" 
        style={{background: 'white'}}
        >
            <FontAwesomeIcon className="text-red-700 text-center w-14 mx-8" icon={faUser} />
            <Link 
            href='/products'
            className="
            transition-all duration-700
            hover:bg-red-700
            hover:text-red-50 
            w-full h-10 
            text-l 
            text-red-700 
            cursor-pointer
            flex
            items-center 
            justify-center">
            Man
            </Link>
            
            <Link href='/'
            className="text-2xl 
            text-red-700
            w-full 
            text-center">
              <h1 style={{fontFamily: 'bodonmt', fontWeight: 'bold'}} >Sport's Mood</h1>
            </Link>
            
            <Link className="
            transition-all duration-700
            hover:bg-red-700 
            w-full h-10 
            text-l 
            text-red-700 
            cursor-pointer 
            hover:text-red-50 
            flex 
            items-center 
            justify-center"
            href='/products'>
              <h2 style={{fontFamily: 'cabin'}}>Woman</h2>
            </Link>
            <FontAwesomeIcon className="text-red-700 text-center w-14 mx-8" icon={faBagShopping} />
        </header>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
