import type { Metadata } from "next";
import './handle.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSurprise, faUser,  } from "@fortawesome/free-regular-svg-icons";
import { faBoltLightning, faFire, faMars, faPlus, faTicket, faTrash, faVenus, faWandMagicSparkles } from "@fortawesome/free-solid-svg-icons"

import Link from "next/link";


export const metadata: Metadata = {
  title: "Administration",
  description: "Generated by Beka Dugladze",
};
export default function AdminLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
            <section>
                <div className="flex flex-col tablet:flex-row w-full tablet:h-screen justify-between">
                    {/* Sidebar */}
                    <div className="bg-red-700 pt-0 tablet:pt-16 tablet:w-48">
                        <ul className="tablet:text-center flex justify-start flex-row flex-nowrap overflow-auto tablet:justify-center tablet:flex-col ul">
                            {/* Sidebar Links */}
                            <Link href='/administration/handle'><li><FontAwesomeIcon icon={faUser} style={{maxHeight: '20px', marginRight: '5px'}}/> User</li></Link>
                            <Link href='/administration/handle/additem'><li><FontAwesomeIcon icon={faPlus} style={{maxHeight: '20px', marginRight: '5px'}}/> Add Item</li></Link>
                            <Link href='/administration/handle/new'><li><FontAwesomeIcon icon={faWandMagicSparkles} style={{maxHeight: '20px', marginRight: '5px'}}/> New Collection</li></Link>
                            <Link href='/administration/handle/trend'><li><FontAwesomeIcon icon={faBoltLightning} style={{maxHeight: '20px', marginRight: '5px'}}/> The Most Trended</li></Link>
                            <Link href='/administration/handle/men'><li><FontAwesomeIcon icon={faMars} style={{maxHeight: '20px', marginRight: '5px'}}/> Men</li></Link>
                            <Link href='/administration/handle/women'><li><FontAwesomeIcon icon={faVenus} style={{maxHeight: '20px', marginRight: '5px'}}/> Women</li></Link>
                            <Link href='/administration/handle/saled'><li><FontAwesomeIcon icon={faFire} style={{maxHeight: '20px', marginRight: '5px'}}/> saled</li></Link>
                            <Link href='/administration/handle/orders'><li><FontAwesomeIcon icon={faTicket} style={{maxHeight: '20px', marginRight: '5px'}}/> Orders</li></Link>
                        </ul>
                    </div>
                    {/* Main Content */}
                    {children}
                </div>
            </section>
    )
}
